# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa9a634503be2a34b5faf5a7266345f3c0b6515eeca36024d3ac00a3c7e526c052d7fcee559b04110631e588b25e1e6789d0edc6e1c51ac99cbeacead48c40f0

test:
  secret_key_base: b220d86719b186ae1d1ffc04b8b9284d98776f1987822a190398da26882dac327e3ff50387d02c96cd6f711d062b836b256697128390ad2bb583cdd29fc234d5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
